=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/somtoolboxPalette.dtd
<!ELEMENT bundles (bundle+)>
<!ELEMENT bundle (shortName, longName?, description?, palette+)>

<!ELEMENT palette (shortName, longName, description?, colors)>
<!ATTLIST palette version CDATA "1.0">
<!ATTLIST palette hidden (true|false) "false">
<!ATTLIST palette group CDATA "">

<!ELEMENT shortName (#PCDATA)>
<!ELEMENT longName (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT colors (color, color+)>
<!ATTLIST colors colorCount CDATA #IMPLIED>
<!ATTLIST colors representation CDATA #IMPLIED>

<!ELEMENT color (gradientPoint?, red, green, blue)>
<!ELEMENT gradientPoint (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/ReliefMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Relief</shortName>
  <longName>Relief map colours</longName>
  <description>Relief map colours as in http://www.ir-facility.org/IRFS2007Presentations/11A_Blanchard_Handling%20search%20results.pps</description>
  <colors>
    <color>
      <red>171</red>
      <green>205</green>
      <blue>214</blue>
    </color>
    <color>
      <red>143</red>
      <green>149</green>
      <blue>150</blue>
    </color>
    <color>
      <red>143</red>
      <green>152</green>
      <blue>152</blue>
    </color>
    <color>
      <red>159</red>
      <green>187</green>
      <blue>155</blue>
    </color>
    <color>
      <red>145</red>
      <green>178</green>
      <blue>147</blue>
    </color>
    <color>
      <red>130</red>
      <green>164</green>
      <blue>131</blue>
    </color>
    <color>
      <red>132</red>
      <green>150</green>
      <blue>132</blue>
    </color>
    <color>
      <red>163</red>
      <green>157</green>
      <blue>148</blue>
    </color>
    <color>
      <red>144</red>
      <green>138</green>
      <blue>133</blue>
    </color>
    <color>
      <red>214</red>
      <green>214</green>
      <blue>214</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Matlab-SOMToolbox-UMatrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="RGB">
  <shortName>M-SOMToolbox</shortName>
  <longName>Matlab SOMToolbox UMatrix</longName>
  <description />
  <colors representation="real">
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.5625</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.6250</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.6875</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.7500</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.8125</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.8750</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0.9375</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.0625</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.1250</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.1875</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.2500</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.3125</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.3750</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.4375</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.5000</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.5625</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.6250</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.6875</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.7500</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.8125</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.8750</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>0.9375</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0</red>
      <green>1.0000</green>
      <blue>1.0000</blue>
    </color>
    <color>
      <red>0.0625</red>
      <green>1.0000</green>
      <blue>0.9375</blue>
    </color>
    <color>
      <red>0.1250</red>
      <green>1.0000</green>
      <blue>0.8750</blue>
    </color>
    <color>
      <red>0.1875</red>
      <green>1.0000</green>
      <blue>0.8125</blue>
    </color>
    <color>
      <red>0.2500</red>
      <green>1.0000</green>
      <blue>0.7500</blue>
    </color>
    <color>
      <red>0.3125</red>
      <green>1.0000</green>
      <blue>0.6875</blue>
    </color>
    <color>
      <red>0.3750</red>
      <green>1.0000</green>
      <blue>0.6250</blue>
    </color>
    <color>
      <red>0.4375</red>
      <green>1.0000</green>
      <blue>0.5625</blue>
    </color>
    <color>
      <red>0.5000</red>
      <green>1.0000</green>
      <blue>0.5000</blue>
    </color>
    <color>
      <red>0.5625</red>
      <green>1.0000</green>
      <blue>0.4375</blue>
    </color>
    <color>
      <red>0.6250</red>
      <green>1.0000</green>
      <blue>0.3750</blue>
    </color>
    <color>
      <red>0.6875</red>
      <green>1.0000</green>
      <blue>0.3125</blue>
    </color>
    <color>
      <red>0.7500</red>
      <green>1.0000</green>
      <blue>0.2500</blue>
    </color>
    <color>
      <red>0.8125</red>
      <green>1.0000</green>
      <blue>0.1875</blue>
    </color>
    <color>
      <red>0.8750</red>
      <green>1.0000</green>
      <blue>0.1250</blue>
    </color>
    <color>
      <red>0.9375</red>
      <green>1.0000</green>
      <blue>0.0625</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>1.0000</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.9375</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.8750</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.8125</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.7500</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.6875</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.6250</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.5625</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.5000</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.4375</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.3750</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.3125</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.2500</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.1875</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.1250</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0.0625</green>
      <blue>0</blue>
    </color>
    <color>
      <red>1.0000</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.9375</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.8750</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.8125</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.7500</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.6875</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.6250</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.5625</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0.5000</red>
      <green>0</green>
      <blue>0</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/TuxTerrain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" hidden="true">
  <shortName>TuxTerrain</shortName>
  <longName>Tuxracer Terrain Palette</longName>
  <description>The Palette for the TuxRacer Terrains</description>
  <colors>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <red>127</red>
      <green>127</green>
      <blue>127</blue>
    </color>
    <color>
      <red>127</red>
      <green>127</green>
      <blue>127</blue>
    </color>
    <color>
      <red>127</red>
      <green>127</green>
      <blue>127</blue>
    </color>
    <color>
      <red>127</red>
      <green>127</green>
      <blue>127</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/CartographyLessWater256.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>CartographyLessWater256</shortName>
  <longName>Cartography Color, 256 Gradient, less water</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>128</blue>
    </color>
    <color>
      <gradientPoint>0.15</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.35</gradientPoint>
      <red>0</red>
      <green>128</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.47</gradientPoint>
      <red>240</red>
      <green>240</green>
      <blue>64</blue>
    </color>
    <color>
      <gradientPoint>0.57</gradientPoint>
      <red>32</red>
      <green>160</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.7</gradientPoint>
      <red>224</red>
      <green>224</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.9</gradientPoint>
      <red>128</red>
      <green>128</green>
      <blue>128</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/matlab-sdh-rgb.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Matlab SDH</shortName>
  <longName>Matlab SDH</longName>
  <description>SDH Palette as in the original MATLAB implementation</description>
  <colors>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>128</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>134</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>140</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>147</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>153</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>159</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>166</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>172</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>179</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>185</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>191</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>198</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>204</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>210</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>217</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>223</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>230</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>236</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>242</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>249</blue>
    </color>
    <color>
      <red>0</red>
      <green>0</green>
      <blue>255</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>77</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>77</blue>
    </color>
    <color>
      <red>0</red>
      <green>102</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>105</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>107</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>110</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>112</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>115</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>117</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>120</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>122</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>125</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>128</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>130</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>133</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>135</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>138</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>140</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>143</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>145</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>148</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>150</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>153</green>
      <blue>0</blue>
    </color>
    <color>
      <red>0</red>
      <green>153</green>
      <blue>0</blue>
    </color>
    <color>
      <red>7</red>
      <green>155</green>
      <blue>7</blue>
    </color>
    <color>
      <red>14</red>
      <green>158</green>
      <blue>14</blue>
    </color>
    <color>
      <red>22</red>
      <green>160</green>
      <blue>22</blue>
    </color>
    <color>
      <red>30</red>
      <green>162</green>
      <blue>30</blue>
    </color>
    <color>
      <red>37</red>
      <green>165</green>
      <blue>37</blue>
    </color>
    <color>
      <red>46</red>
      <green>167</green>
      <blue>46</blue>
    </color>
    <color>
      <red>54</red>
      <green>169</green>
      <blue>54</blue>
    </color>
    <color>
      <red>62</red>
      <green>172</green>
      <blue>62</blue>
    </color>
    <color>
      <red>71</red>
      <green>174</green>
      <blue>71</blue>
    </color>
    <color>
      <red>80</red>
      <green>176</green>
      <blue>80</blue>
    </color>
    <color>
      <red>89</red>
      <green>179</green>
      <blue>89</blue>
    </color>
    <color>
      <red>179</red>
      <green>179</green>
      <blue>179</blue>
    </color>
    <color>
      <red>189</red>
      <green>189</green>
      <blue>189</blue>
    </color>
    <color>
      <red>200</red>
      <green>200</green>
      <blue>200</blue>
    </color>
    <color>
      <red>211</red>
      <green>211</green>
      <blue>211</blue>
    </color>
    <color>
      <red>222</red>
      <green>222</green>
      <blue>222</blue>
    </color>
    <color>
      <red>233</red>
      <green>233</green>
      <blue>233</blue>
    </color>
    <color>
      <red>244</red>
      <green>244</green>
      <blue>244</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/GISsmooth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>GISsmooth</shortName>
  <longName>GIS colours, smooth</longName>
  <description />
  <colors>
    <color>
      <red>55</red>
      <green>165</green>
      <blue>75</blue>
    </color>
    <color>
      <red>60</red>
      <green>170</green>
      <blue>80</blue>
    </color>
    <color>
      <red>110</red>
      <green>190</green>
      <blue>120</blue>
    </color>
    <color>
      <red>115</red>
      <green>195</green>
      <blue>125</blue>
    </color>
    <color>
      <red>120</red>
      <green>200</green>
      <blue>130</blue>
    </color>
    <color>
      <red>135</red>
      <green>200</green>
      <blue>140</blue>
    </color>
    <color>
      <red>140</red>
      <green>205</green>
      <blue>145</blue>
    </color>
    <color>
      <red>145</red>
      <green>210</green>
      <blue>150</blue>
    </color>
    <color>
      <red>170</red>
      <green>160</green>
      <blue>100</blue>
    </color>
    <color>
      <red>170</red>
      <green>160</green>
      <blue>100</blue>
    </color>
    <color>
      <red>170</red>
      <green>160</green>
      <blue>100</blue>
    </color>
    <color>
      <red>190</red>
      <green>180</green>
      <blue>125</blue>
    </color>
    <color>
      <red>195</red>
      <green>185</green>
      <blue>130</blue>
    </color>
    <color>
      <red>200</red>
      <green>190</green>
      <blue>135</blue>
    </color>
    <color>
      <red>230</red>
      <green>220</green>
      <blue>160</blue>
    </color>
    <color>
      <red>235</red>
      <green>225</green>
      <blue>165</blue>
    </color>
    <color>
      <red>230</red>
      <green>220</green>
      <blue>160</blue>
    </color>
    <color>
      <red>205</red>
      <green>160</green>
      <blue>105</blue>
    </color>
    <color>
      <red>200</red>
      <green>155</green>
      <blue>100</blue>
    </color>
    <color>
      <red>195</red>
      <green>150</green>
      <blue>95</blue>
    </color>
    <color>
      <red>185</red>
      <green>125</green>
      <blue>75</blue>
    </color>
    <color>
      <red>180</red>
      <green>120</green>
      <blue>70</blue>
    </color>
    <color>
      <red>185</red>
      <green>115</green>
      <blue>65</blue>
    </color>
    <color>
      <red>185</red>
      <green>95</green>
      <blue>40</blue>
    </color>
    <color>
      <red>185</red>
      <green>90</green>
      <blue>35</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Mountains10.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Mountains10</shortName>
  <longName>Cartography Color, Mountains 10, 10 Colors</longName>
  <description />
  <colors>
    <color>
      <red>175</red>
      <green>240</green>
      <blue>232</blue>
    </color>
    <color>
      <red>220</red>
      <green>250</green>
      <blue>178</blue>
    </color>
    <color>
      <red>83</red>
      <green>183</green>
      <blue>59</blue>
    </color>
    <color>
      <red>101</red>
      <green>148</green>
      <blue>52</blue>
    </color>
    <color>
      <red>240</red>
      <green>157</green>
      <blue>1</blue>
    </color>
    <color>
      <red>139</red>
      <green>11</green>
      <blue>0</blue>
    </color>
    <color>
      <red>104</red>
      <green>40</green>
      <blue>15</blue>
    </color>
    <color>
      <red>139</red>
      <green>95</green>
      <blue>70</blue>
    </color>
    <color>
      <red>189</red>
      <green>189</green>
      <blue>189</blue>
    </color>
    <color>
      <red>254</red>
      <green>252</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Grayscale16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Single Color">
  <shortName>Grayscale16</shortName>
  <longName>Grayscale, 16 Gradient</longName>
  <description>Grayscale palette well suited for b/w screenshots</description>
  <colors>
    <color>
      <red>50</red>
      <green>50</green>
      <blue>50</blue>
    </color>
    <color>
      <red>62</red>
      <green>62</green>
      <blue>62</blue>
    </color>
    <color>
      <red>75</red>
      <green>75</green>
      <blue>75</blue>
    </color>
    <color>
      <red>88</red>
      <green>88</green>
      <blue>88</blue>
    </color>
    <color>
      <red>101</red>
      <green>101</green>
      <blue>101</blue>
    </color>
    <color>
      <red>114</red>
      <green>114</green>
      <blue>114</blue>
    </color>
    <color>
      <red>126</red>
      <green>126</green>
      <blue>126</blue>
    </color>
    <color>
      <red>139</red>
      <green>139</green>
      <blue>139</blue>
    </color>
    <color>
      <red>152</red>
      <green>152</green>
      <blue>152</blue>
    </color>
    <color>
      <red>165</red>
      <green>165</green>
      <blue>165</blue>
    </color>
    <color>
      <red>178</red>
      <green>178</green>
      <blue>178</blue>
    </color>
    <color>
      <red>190</red>
      <green>190</green>
      <blue>190</blue>
    </color>
    <color>
      <red>203</red>
      <green>203</green>
      <blue>203</blue>
    </color>
    <color>
      <red>216</red>
      <green>216</green>
      <blue>216</blue>
    </color>
    <color>
      <red>229</red>
      <green>229</green>
      <blue>229</blue>
    </color>
    <color>
      <red>242</red>
      <green>242</green>
      <blue>242</blue>
    </color>
  </colors>
</palette>
