=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/somtoolboxPalette.dtd
<!ELEMENT bundles (bundle+)>
<!ELEMENT bundle (shortName, longName?, description?, palette+)>

<!ELEMENT palette (shortName, longName, description?, colors)>
<!ATTLIST palette version CDATA "1.0">
<!ATTLIST palette hidden (true|false) "false">
<!ATTLIST palette group CDATA "">

<!ELEMENT shortName (#PCDATA)>
<!ELEMENT longName (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT colors (color, color+)>
<!ATTLIST colors colorCount CDATA #IMPLIED>
<!ATTLIST colors representation CDATA #IMPLIED>

<!ELEMENT color (gradientPoint?, red, green, blue)>
<!ELEMENT gradientPoint (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Crime.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="RGB">
  <shortName>Crime</shortName>
  <longName>Crime Data</longName>
  <description />
  <colors>
    <color>
      <red>255</red>
      <green>51</green>
      <blue>51</blue>
    </color>
    <color>
      <red>255</red>
      <green>149</green>
      <blue>51</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>51</blue>
    </color>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>129</blue>
    </color>
    <color>
      <red>210</red>
      <green>255</green>
      <blue>147</blue>
    </color>
    <color>
      <red>197</red>
      <green>255</green>
      <blue>163</blue>
    </color>
    <color>
      <red>161</red>
      <green>255</green>
      <blue>203</blue>
    </color>
    <color>
      <red>141</red>
      <green>255</green>
      <blue>219</blue>
    </color>
    <color>
      <red>89</red>
      <green>217</green>
      <blue>255</blue>
    </color>
    <color>
      <red>98</red>
      <green>177</green>
      <blue>255</blue>
    </color>
    <color>
      <red>98</red>
      <green>156</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Mountains256-2c.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Mountains256-2c</shortName>
  <longName>Cartography Color, Mountains 2c, 256 Gradient</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>175</red>
      <green>240</green>
      <blue>232</blue>
    </color>
    <color>
      <gradientPoint>0.125</gradientPoint>
      <red>220</red>
      <green>250</green>
      <blue>178</blue>
    </color>
    <color>
      <gradientPoint>0.25</gradientPoint>
      <red>82</red>
      <green>184</green>
      <blue>59</blue>
    </color>
    <color>
      <gradientPoint>0.375</gradientPoint>
      <red>101</red>
      <green>148</green>
      <blue>52</blue>
    </color>
    <color>
      <gradientPoint>0.547</gradientPoint>
      <red>240</red>
      <green>157</green>
      <blue>1</blue>
    </color>
    <color>
      <gradientPoint>0.72</gradientPoint>
      <red>139</red>
      <green>11</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.83</gradientPoint>
      <red>104</red>
      <green>40</green>
      <blue>15</blue>
    </color>
    <color>
      <gradientPoint>0.94</gradientPoint>
      <red>139</red>
      <green>95</green>
      <blue>70</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>200</red>
      <green>200</green>
      <blue>205</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Cartography256.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Cartography256</shortName>
  <longName>Cartography Color, 256 Gradient</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>128</blue>
    </color>
    <color>
      <gradientPoint>0.375</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.5</gradientPoint>
      <red>0</red>
      <green>128</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.53125</gradientPoint>
      <red>240</red>
      <green>240</green>
      <blue>64</blue>
    </color>
    <color>
      <gradientPoint>0.5625</gradientPoint>
      <red>32</red>
      <green>160</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.6875</gradientPoint>
      <red>224</red>
      <green>224</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.875</gradientPoint>
      <red>128</red>
      <green>128</green>
      <blue>128</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/GIS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>GIS</shortName>
  <longName>GIS colours</longName>
  <description />
  <colors>
    <color>
      <red>55</red>
      <green>165</green>
      <blue>75</blue>
    </color>
    <color>
      <red>115</red>
      <green>195</green>
      <blue>125</blue>
    </color>
    <color>
      <red>140</red>
      <green>205</green>
      <blue>145</blue>
    </color>
    <color>
      <red>170</red>
      <green>160</green>
      <blue>100</blue>
    </color>
    <color>
      <red>195</red>
      <green>185</green>
      <blue>130</blue>
    </color>
    <color>
      <red>235</red>
      <green>225</green>
      <blue>165</blue>
    </color>
    <color>
      <red>200</red>
      <green>155</green>
      <blue>100</blue>
    </color>
    <color>
      <red>180</red>
      <green>120</green>
      <blue>70</blue>
    </color>
    <color>
      <red>185</red>
      <green>90</green>
      <blue>35</blue>
    </color>
  </colors>
</palette>
