=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/somtoolboxPalette.dtd
<!ELEMENT bundles (bundle+)>
<!ELEMENT bundle (shortName, longName?, description?, palette+)>

<!ELEMENT palette (shortName, longName, description?, colors)>
<!ATTLIST palette version CDATA "1.0">
<!ATTLIST palette hidden (true|false) "false">
<!ATTLIST palette group CDATA "">

<!ELEMENT shortName (#PCDATA)>
<!ELEMENT longName (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT colors (color, color+)>
<!ATTLIST colors colorCount CDATA #IMPLIED>
<!ATTLIST colors representation CDATA #IMPLIED>

<!ELEMENT color (gradientPoint?, red, green, blue)>
<!ELEMENT gradientPoint (#PCDATA)>
<!ELEMENT red (#PCDATA)>
<!ELEMENT green (#PCDATA)>
<!ELEMENT blue (#PCDATA)>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/TuxElevation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" hidden="true">
  <shortName>TuxElevation</shortName>
  <longName>TuxRacer Elevation Palette</longName>
  <description>This Palette is used for the TuxRacer</description>
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.35</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.9</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/RGB256.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="RGB">
  <shortName>RGB256</shortName>
  <longName>RGB, 256 Gradient</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>255</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.25</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.5</gradientPoint>
      <red>0</red>
      <green>255</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.75</gradientPoint>
      <red>0</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Redscale32.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Single Color">
  <shortName>Redscale32</shortName>
  <longName>Redscale, 32 Gradient</longName>
  <description>Original palette for the Component Planes</description>
  <colors>
    <color>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <red>255</red>
      <green>248</green>
      <blue>248</blue>
    </color>
    <color>
      <red>255</red>
      <green>241</green>
      <blue>240</blue>
    </color>
    <color>
      <red>255</red>
      <green>234</green>
      <blue>232</blue>
    </color>
    <color>
      <red>255</red>
      <green>227</green>
      <blue>224</blue>
    </color>
    <color>
      <red>255</red>
      <green>220</green>
      <blue>216</blue>
    </color>
    <color>
      <red>255</red>
      <green>213</green>
      <blue>208</blue>
    </color>
    <color>
      <red>255</red>
      <green>206</green>
      <blue>200</blue>
    </color>
    <color>
      <red>255</red>
      <green>199</green>
      <blue>192</blue>
    </color>
    <color>
      <red>255</red>
      <green>192</green>
      <blue>184</blue>
    </color>
    <color>
      <red>255</red>
      <green>185</green>
      <blue>176</blue>
    </color>
    <color>
      <red>255</red>
      <green>178</green>
      <blue>168</blue>
    </color>
    <color>
      <red>255</red>
      <green>171</green>
      <blue>160</blue>
    </color>
    <color>
      <red>255</red>
      <green>164</green>
      <blue>152</blue>
    </color>
    <color>
      <red>255</red>
      <green>157</green>
      <blue>144</blue>
    </color>
    <color>
      <red>255</red>
      <green>150</green>
      <blue>136</blue>
    </color>
    <color>
      <red>255</red>
      <green>143</green>
      <blue>128</blue>
    </color>
    <color>
      <red>255</red>
      <green>136</green>
      <blue>120</blue>
    </color>
    <color>
      <red>255</red>
      <green>129</green>
      <blue>112</blue>
    </color>
    <color>
      <red>255</red>
      <green>122</green>
      <blue>104</blue>
    </color>
    <color>
      <red>255</red>
      <green>115</green>
      <blue>96</blue>
    </color>
    <color>
      <red>255</red>
      <green>108</green>
      <blue>88</blue>
    </color>
    <color>
      <red>255</red>
      <green>101</green>
      <blue>80</blue>
    </color>
    <color>
      <red>255</red>
      <green>94</green>
      <blue>72</blue>
    </color>
    <color>
      <red>255</red>
      <green>87</green>
      <blue>64</blue>
    </color>
    <color>
      <red>255</red>
      <green>80</green>
      <blue>56</blue>
    </color>
    <color>
      <red>255</red>
      <green>73</green>
      <blue>48</blue>
    </color>
    <color>
      <red>255</red>
      <green>66</green>
      <blue>40</blue>
    </color>
    <color>
      <red>255</red>
      <green>59</green>
      <blue>32</blue>
    </color>
    <color>
      <red>255</red>
      <green>52</green>
      <blue>24</blue>
    </color>
    <color>
      <red>255</red>
      <green>45</green>
      <blue>16</blue>
    </color>
    <color>
      <red>255</red>
      <green>38</green>
      <blue>8</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Mountains256-2b.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Mountains256-2b</shortName>
  <longName>Cartography Color, Mountains 2b, 256 Gradient</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>175</red>
      <green>240</green>
      <blue>232</blue>
    </color>
    <color>
      <gradientPoint>0.125</gradientPoint>
      <red>220</red>
      <green>250</green>
      <blue>178</blue>
    </color>
    <color>
      <gradientPoint>0.25</gradientPoint>
      <red>82</red>
      <green>184</green>
      <blue>59</blue>
    </color>
    <color>
      <gradientPoint>0.375</gradientPoint>
      <red>101</red>
      <green>148</green>
      <blue>52</blue>
    </color>
    <color>
      <gradientPoint>0.5</gradientPoint>
      <red>240</red>
      <green>157</green>
      <blue>1</blue>
    </color>
    <color>
      <gradientPoint>0.625</gradientPoint>
      <red>139</red>
      <green>11</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.75</gradientPoint>
      <red>104</red>
      <green>40</green>
      <blue>15</blue>
    </color>
    <color>
      <gradientPoint>0.875</gradientPoint>
      <red>139</red>
      <green>95</green>
      <blue>70</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>189</red>
      <green>189</green>
      <blue>189</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/SkyYellow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Sky">
  <shortName>SkyYellow</shortName>
  <longName>Sky with Galaxies - Yellow</longName>
  <description>A night view of galaxies on the sky</description>
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.6</gradientPoint>
      <red>32</red>
      <green>32</green>
      <blue>32</blue>
    </color>
    <color>
      <gradientPoint>0.8</gradientPoint>
      <red>96</red>
      <green>96</green>
      <blue>96</blue>
    </color>
    <color>
      <gradientPoint>0.89</gradientPoint>
      <red>153</red>
      <green>153</green>
      <blue>153</blue>
    </color>
    <color>
      <gradientPoint>0.92</gradientPoint>
      <red>204</red>
      <green>204</green>
      <blue>204</blue>
    </color>
    <color>
      <gradientPoint>0.96</gradientPoint>
      <red>255</red>
      <green>244</green>
      <blue>164</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>209</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/MetroMapUMatrix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" hidden="true">
  <shortName>MetroMap</shortName>
  <longName>Metro Map UMatrix 'River'</longName>
  <description />
  <colors>
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.25</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.3</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>0.31</gradientPoint>
      <red>122</red>
      <green>122</green>
      <blue>255</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>0</red>
      <green>0</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Mountains256-2a.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Cartography">
  <shortName>Mountains256-2a</shortName>
  <longName>Cartography Color, Mountains 2a, 256 Gradient</longName>
  <description />
  <colors colorCount="256">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>220</red>
      <green>250</green>
      <blue>178</blue>
    </color>
    <color>
      <gradientPoint>0.125</gradientPoint>
      <red>82</red>
      <green>184</green>
      <blue>59</blue>
    </color>
    <color>
      <gradientPoint>0.25</gradientPoint>
      <red>101</red>
      <green>148</green>
      <blue>52</blue>
    </color>
    <color>
      <gradientPoint>0.375</gradientPoint>
      <red>240</red>
      <green>157</green>
      <blue>1</blue>
    </color>
    <color>
      <gradientPoint>0.5</gradientPoint>
      <red>139</red>
      <green>11</green>
      <blue>0</blue>
    </color>
    <color>
      <gradientPoint>0.625</gradientPoint>
      <red>104</red>
      <green>40</green>
      <blue>15</blue>
    </color>
    <color>
      <gradientPoint>0.75</gradientPoint>
      <red>139</red>
      <green>95</green>
      <blue>70</blue>
    </color>
    <color>
      <gradientPoint>0.875</gradientPoint>
      <red>189</red>
      <green>189</green>
      <blue>189</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>254</red>
      <green>252</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>

=== BenBach/sos-dendrogram/somtoolbox/src/core/rsc/palettes/Grayscale8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE palette SYSTEM "somtoolboxPalette.dtd">

<!-- Color-Palette for SOMViewer -->
<palette version="1.0" group="Single Color">
  <shortName>Grayscale8</shortName>
  <longName>Grayscale, 8 Gradient</longName>
  <description>Grayscale palette well suited for b/w screenshots</description>
  <colors colorCount="8">
    <color>
      <gradientPoint>0.0</gradientPoint>
      <red>50</red>
      <green>50</green>
      <blue>50</blue>
    </color>
    <color>
      <gradientPoint>1.0</gradientPoint>
      <red>255</red>
      <green>255</green>
      <blue>255</blue>
    </color>
  </colors>
</palette>
